"""
Django settings for eshop project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import environ
import dj_database_url
from pathlib import Path
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


SECRET_KEY = env('SECRET_KEY')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEBUG = env.bool('DEBUG')


ALLOWED_HOSTS = [
    "shuddho.net",
    "www.shuddho.net",   
    "187.127.214.53",
    "127.0.0.1",
    "localhost",
]

CSRF_TRUSTED_ORIGINS = [  
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "https://shuddho.net",
    "https://www.shuddho.net", 
]

# Application definition
INSTALLED_APPS = [
    'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'shop',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    "crispy_forms",
    "crispy_bootstrap5",
    # 'cloudinary',
    # 'cloudinary_storage',
    
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = 'eshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'shop.context_processors.meta_pixel',
                'django.contrib.messages.context_processors.messages',
                # `allauth` needs this from django
                'shop.context_processors.cart_items_count',
                'shop.context_processors.category_menu',
            ],
        },
    },
]

SITE_ID = 1  # new

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

WSGI_APPLICATION = 'eshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': dj_database_url.config(
        default=env('DATABASE_URL'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# static file
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# media file 

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# cloudinary.config(
#     cloud_name = os.environ.get("CLOUDINARY_CLOUD_NAME"),
#     api_key = os.environ.get("CLOUDINARY_API_KEY"),
#     api_secret = os.environ.get("CLOUDINARY_API_SECRET")
# )

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Login URL
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_SESSION_REMEMBER = True 
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# SSL Commerz setup
SSLCOMMERZ_STORE_ID = env('SSLCOMMERZ_STORE_ID')
SSLCOMMERZ_STORE_PASSWORD = env('SSLCOMMERZ_STORE_PASSWORD')
SSLCOMMERZ_PAYMENT_URL = env('SSLCOMMERZ_PAYMENT_URL')
SSLCOMMERZ_VALIDATION_URL = env('SSLCOMMERZ_VALIDATION_URL')

# email setup
EMAIL_BACKEND = env('EMAIL_BACKEND')
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_PORT = env.int('EMAIL_PORT')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS')
ADMIN_EMAIL = env('ADMIN_EMAIL', default=EMAIL_HOST_USER)

# Meta pixel setup
META_PIXEL_ID = env('META_PIXEL_ID', default='')

# EXTRA SECURITY
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG




# Django jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "MuradMartBD Admin",
    "site_header": "MuradMartBD",
    "site_brand": "MuradMartBD",
    "welcome_sign": "MuradMartBD Admin Panel-এ স্বাগতম",
    "copyright": "MuradMartBD",
    "search_model": ["shop.Product", "shop.Category"],

    "topmenu_links": [
        {"name": "Home", "url": "home", "permissions": ["auth.view_user"]},
        {"model": "shop.product"},
        {"model": "shop.category"},
    ],

    "order_with_respect_to": ["shop", "shop.category", "shop.product", "shop.order", "auth"],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "shop.Category": "fas fa-sitemap",
        "shop.Product": "fas fa-box",
        "shop.Order": "fas fa-shopping-cart",
        "shop.OrderItem": "fas fa-receipt",
        "shop.Cart": "fas fa-shopping-basket",
        "shop.CartItem": "fas fa-cart-plus",
        "shop.Rating": "fas fa-star",
    },

    "show_ui_builder": True,   # admin থেকেই থিম customize করার UI দেখাবে
}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-light navbar-white",
    "navbar_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "theme": "flatly",
    "button_classes": {
        "primary": "btn-success",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


# Google diye login
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}
