# Generated by Django 5.2.7 on 2026-03-03 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_session_key_order_session_key_alter_cart_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_key'], name='shop_cart_session_e92239_idx'),
        ),
    ]
