# Generated by Django 6.0.6 on 2026-07-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_parent_alter_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading, e.g. Special Seasonal Discount', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short text under the title')),
                ('image', models.ImageField(help_text='Recommended size: 700x450px', upload_to='promo_banners/')),
                ('button_text', models.CharField(default='Shop Now', max_length=50)),
                ('button_link', models.CharField(blank=True, help_text='Where the button should go. Example: /products/  or  /category/food/', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this banner without deleting it')),
                ('order', models.PositiveIntegerField(default=0, help_text='Smaller number shows first')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional. Leave empty to show now', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional. Leave empty to show forever', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promo Banner',
                'verbose_name_plural': 'Promo Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
