# Generated by Django 6.0.6 on 2026-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_promobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promobanner',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='promobanner',
            name='start_date',
        ),
        migrations.AddField(
            model_name='promobanner',
            name='link',
            field=models.URLField(blank=True, help_text='Optional — where visitors go if they click the banner'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.ImageField(upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Smaller number shows first (0, 1, 2 ...)'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='title',
            field=models.CharField(blank=True, help_text='Internal name only — not shown on the website', max_length=150),
        ),
    ]
