# Generated by Django 6.0.6 on 2026-07-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_promobanner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sale price during flash sale (must be lower than regular price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_end',
            field=models.DateTimeField(blank=True, help_text='Flash sale countdown ends at this date/time', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(default=False, help_text='Show this product in the Flash Sale section'),
        ),
    ]
